version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin    
      - POSTGRES_PASSWORD=admin    
      - POSTGRES_DB=speakers-report
    volumes:
      - speakers-report-pg-data:/bitnami/postgresql

volumes:
  speakers-report-pg-data: