# Stage 1: Builder
FROM node:22-alpine3.20 AS builder
WORKDIR /app

# Copia os arquivos necessários
COPY package*.json ./
RUN npm ci --include=dev

# Copia o restante da aplicação
COPY . .

# Faz o build com NODE_ENV=production (sem migration ainda)
ENV NODE_ENV=production
RUN npm run build

# Stage 2: Production
FROM node:22-alpine3.20 AS production
WORKDIR /app

# Copia apenas os artefatos finais
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package*.json /app/

# Instala o cliente PostgreSQL
RUN apk add --no-cache postgresql-client

COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x entrypoint.sh

ENV NODE_ENV=production

ENTRYPOINT ["./entrypoint-api.sh"]
