services:
  # Banco de produção
  postgres-production:
    image: postgres:17.4-alpine
    container_name: speakers-report-db-production
    environment:
      POSTGRES_USER: ${POSTGRES_USER_PROD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROD}
      POSTGRES_DB: ${POSTGRES_DB_PROD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - speakers-report-pg-data-prod:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  speakers-report-pg-data-prod:
